In [2]:
import pandas as pd

In [ ]:
# list of lists
data = [
    ['Alex', 10],
    ['Bob', 12],
    ['Clarke', 13]
]

df = pd.DataFrame(data)
df

        0   1
0    Alex  10
1     Bob  12
2  Clarke  13

In [10]:
# list of dict
data = [
    {'Name': 'Alex',  'Age': 10},
    {'Name': 'Bob',   'Age': 12},
    {'Name': 'Clarke','Age': 13},
]

df = pd.DataFrame(data)
df

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13

In [11]:
# dict of lists
data = {
    'Name':  ['Alex', 'Bob', 'Clarke'],
    'Age':   [10, 12, 13],
}

df = pd.DataFrame(data)
df

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13

In [14]:
# dict of dict
data = {
    'a': {'Name': 'Alex',  'Age': 10},
    'b': {'Name': 'Bob',   'Age': 12},
    'c': {'Name': 'Clarke','Age': 13},
}

df = pd.DataFrame(data)
df

         a    b       c
Name  Alex  Bob  Clarke
Age     10   12      13

In [15]:
# dict of dict
data = {
    'Name': {'a': 'Alex',  'b': 'Bob', 'c': 'Clarke'},
    'Age': {'a': 10, 'b': 12, 'c':13},
}

df = pd.DataFrame(data)
df

     Name  Age
a    Alex   10
b     Bob   12
c  Clarke   13

In [21]:
df = pd.read_csv("dataset.csv")
df

,name,type_1,type_2,HP,phAtk,phDef,spAtk,spDef,speed,BST,...,weight,catch_rate,base_exp,item_1,item_2,gender_ratio,egg_cycles,growth_rate,egg_group_1,egg_group_2
0,CHIKORITA,GRASS,...,40,50,65,50,65,45,315,...,140,45,64,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT
1,BAYLEEF,GRASS,...,65,65,80,65,80,65,420,...,350,45,141,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT
2,MEGANIUM,GRASS,FAIRY,80,80,110,75,110,75,530,...,2220,45,208,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT
3,CYNDAQUIL,FIRE,...,40,60,40,60,50,65,315,...,170,45,65,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
4,QUILAVA,FIRE,...,60,65,60,85,65,85,420,...,420,45,142,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,GRAVELER,ROCK,...,55,95,120,45,45,40,400,...,2320,120,134,NO_ITEM,EVERSTONE,F50,15,MEDIUM_SLOW,MINERAL,...
96,GOLEM,ROCK,...,80,105,160,50,65,40,500,...,6620,45,177,NO_ITEM,EVERSTONE,F50,15,MEDIUM_SLOW,MINERAL,...
97,GASTLY,GHOST,...,30,35,30,95,35,75,300,...,2,190,95,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...
98,HAUNTER,GHOST,...,45,60,45,100,55,95,400,...,2,90,126,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...
99,GENGAR,GHOST,...,60,85,60,110,75,110,500,...,890,45,190,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,.

In [ ]:
df.to_csv("output.csv", index=False)
df.to_json("output.json", index=False)

In [24]:
df.head(3)

,name,type_1,type_2,HP,phAtk,phDef,spAtk,spDef,speed,BST,...,weight,catch_rate,base_exp,item_1,item_2,gender_ratio,egg_cycles,growth_rate,egg_group_1,egg_group_2
0,CHIKORITA,GRASS,...,40,50,65,50,65,45,315,...,140,45,64,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT
1,BAYLEEF,GRASS,...,65,65,80,65,80,65,420,...,350,45,141,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT
2,MEGANIUM,GRASS,FAIRY,80,80,110,75,110,75,530,...,2220,45,208,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT

In [25]:
df.tail(3)

,name,type_1,type_2,HP,phAtk,phDef,spAtk,spDef,speed,BST,...,weight,catch_rate,base_exp,item_1,item_2,gender_ratio,egg_cycles,growth_rate,egg_group_1,egg_group_2
97,GASTLY,GHOST,...,30,35,30,95,35,75,300,...,2,190,95,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...
98,HAUNTER,GHOST,...,45,60,45,100,55,95,400,...,2,90,126,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...
99,GENGAR,GHOST,...,60,85,60,110,75,110,500,...,890,45,190,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,.

In [62]:
print(df.shape)
print(len(df))
print(len(df.columns))
print(df.columns)

(100, 23)
100
23
Index(['name', 'type_1', 'type_2', 'HP', 'phAtk', 'phDef', 'spAtk', 'spDef',
       'speed', 'BST', 'evolves_from', 'evolves_into', 'height', 'weight',
       'catch_rate', 'base_exp', 'item_1', 'item_2', 'gender_ratio',
       'egg_cycles', 'growth_rate', 'egg_group_1', 'egg_group_2'],
      dtype='str')

In [ ]:
row = df.loc[1 , :]

print(type(row))
row

<class 'pandas.Series'>

name                BAYLEEF
type_1                GRASS
type_2                  ...
HP                       65
phAtk                    65
phDef                    80
spAtk                    65
spDef                    80
speed                    65
BST                     420
evolves_from      CHIKORITA
evolves_into       MEGANIUM
height                  311
weight                  350
catch_rate               45
base_exp                141
item_1              NO_ITEM
item_2                  ...
gender_ratio          F12_5
egg_cycles               20
growth_rate     MEDIUM_SLOW
egg_group_1         MONSTER
egg_group_2           PLANT
Name: 1, dtype: object

In [55]:
col = df.loc[ : , 'type_2']

print(type(col))
col

<class 'pandas.Series'>

0       ...
1       ...
2     FAIRY
3       ...
4       ...
      ...
95      ...
96      ...
97      ...
98      ...
99      ...
Name: type_2, Length: 100, dtype: str

In [ ]:
cell = df.loc[ 1 , 'HP' ]

print(type(cell))
cell

<class 'numpy.int64'>

np.int64(65)

In [64]:
table = df.loc[ : , : ]

print(type(table))
table

<class 'pandas.DataFrame'>

,name,type_1,type_2,HP,phAtk,phDef,spAtk,spDef,speed,BST,...,weight,catch_rate,base_exp,item_1,item_2,gender_ratio,egg_cycles,growth_rate,egg_group_1,egg_group_2
0,CHIKORITA,GRASS,...,40,50,65,50,65,45,315,...,140,45,64,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT
1,BAYLEEF,GRASS,...,65,65,80,65,80,65,420,...,350,45,141,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT
2,MEGANIUM,GRASS,FAIRY,80,80,110,75,110,75,530,...,2220,45,208,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT
3,CYNDAQUIL,FIRE,...,40,60,40,60,50,65,315,...,170,45,65,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
4,QUILAVA,FIRE,...,60,65,60,85,65,85,420,...,420,45,142,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,GRAVELER,ROCK,...,55,95,120,45,45,40,400,...,2320,120,134,NO_ITEM,EVERSTONE,F50,15,MEDIUM_SLOW,MINERAL,...
96,GOLEM,ROCK,...,80,105,160,50,65,40,500,...,6620,45,177,NO_ITEM,EVERSTONE,F50,15,MEDIUM_SLOW,MINERAL,...
97,GASTLY,GHOST,...,30,35,30,95,35,75,300,...,2,190,95,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...
98,HAUNTER,GHOST,...,45,60,45,100,55,95,400,...,2,90,126,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...
99,GENGAR,GHOST,...,60,85,60,110,75,110,500,...,890,45,190,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,.