In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("dataset.csv")
df

,species_ID,type_1,type_2,HP,phAtk,phDef,spAtk,spDef,speed,BST,...,weight,catch_rate,base_exp,item_1,item_2,gender_ratio,egg_cycles,growth_rate,egg_group_1,egg_group_2
0,CHIKORITA,GRASS,...,40,50,65,50,65,45,315,...,140,45,64,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT
1,BAYLEEF,GRASS,...,65,65,80,65,80,65,420,...,350,45,141,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT
2,MEGANIUM,GRASS,FAIRY,80,80,110,75,110,75,530,...,2220,45,208,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT
3,CYNDAQUIL,FIRE,...,40,60,40,60,50,65,315,...,170,45,65,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
4,QUILAVA,FIRE,...,60,65,60,85,65,85,420,...,420,45,142,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,GRAVELER,ROCK,...,55,95,120,45,45,40,400,...,2320,120,134,NO_ITEM,EVERSTONE,F50,15,MEDIUM_SLOW,MINERAL,...
96,GOLEM,ROCK,...,80,105,160,50,65,40,500,...,6620,45,177,NO_ITEM,EVERSTONE,F50,15,MEDIUM_SLOW,MINERAL,...
97,GASTLY,GHOST,...,30,35,30,95,35,75,300,...,2,190,95,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...
98,HAUNTER,GHOST,...,45,60,45,100,55,95,400,...,2,90,126,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...
99,GENGAR,GHOST,...,60,85,60,110,75,110,500,...,890,45,190,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,.

In [ ]:
type(df.head(3))

pandas.Index

In [ ]:
flying_mons = df.loc[ df['HP']>100, ['species_ID', 'HP'] ].reset_index(drop=True)
flying_mons

   species_ID   HP
0     NOCTOWL  110
1     LANTURN  115
2  DOOMSPARCE  125
3  KANGASKHAN  105
4  JIGGLYPUFF  115
5  WIGGLYTUFF  140

In [ ]:
physical_atkrs = df.loc[ df['phAtk']>df['spAtk'], : ].reset_index(drop=True)
physical_atkrs

In [ ]:
offensive = df.loc[ (df['phAtk'] + df['spAtk'])>(df['phDef'] + df['spDef']), : ].reset_index(drop=True)
offensive

,species_ID,type_1,type_2,HP,phAtk,phDef,spAtk,spDef,speed,BST,...,weight,catch_rate,base_exp,item_1,item_2,gender_ratio,egg_cycles,growth_rate,egg_group_1,egg_group_2
0,CYNDAQUIL,FIRE,...,40,60,40,60,50,65,315,...,170,45,65,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
1,QUILAVA,FIRE,...,60,65,60,85,65,85,420,...,420,45,142,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
2,TYPHLOSION,FIRE,...,80,85,80,105,85,95,530,...,1750,45,209,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
3,CROCONAW,WATER,...,65,85,80,65,65,60,420,...,550,45,143,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,WATER_1
4,FERALIGATR,WATER,...,85,105,90,90,80,80,530,...,1960,45,210,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,WATER_1
5,NATU,FLYING,PSYCHIC,40,40,25,60,25,60,250,...,40,190,73,NO_ITEM,...,F50,20,MEDIUM_FAST,FLYING,...
6,XATU,FLYING,PSYCHIC,65,60,55,115,70,105,470,...,330,75,171,NO_ITEM,...,F50,20,MEDIUM_FAST,FLYING,...
7,PICHU,ELECTRIC,...,20,40,15,35,35,55,200,...,40,190,42,NO_ITEM,BERRY,F50,10,MEDIUM_FAST,NONE,...
8,PIKACHU,ELECTRIC,...,35,60,40,75,50,90,350,...,130,190,82,NO_ITEM,BERRY,F50,10,MEDIUM_FAST,GROUND,FAIRY
9,RAICHU,ELECTRIC,...,60,90,55,100,85,110,500,...,660,75,122,NO_ITEM,BERRY,F50,10,MEDIUM_FAST,GROUND,FAIRY
10,SPINARAK,BUG,POISON,40,60,40,40,40,30,250,...,190,255,54,NO_ITEM,...,F50,15,FAST,BUG,...
11,PARAS,BUG,GRASS,35,55,45,45,45,25,250,...,120,190,70,TINYMUSHROOM,BIG_MUSHROOM,F50,20,MEDIUM_FAST,BUG,PLANT
12,PARASECT,BUG,GRASS,50,130,90,60,90,30,450,...,650,75,128,TINYMUSHROOM,BIG_MUSHROOM,F50,20,MEDIUM_FAST,BUG,PLANT
13,GOLBAT,POISON,FLYING,70,80,65,65,75,85,440,...,1210,90,171,NO_ITEM,...,F50,15,MEDIUM_FAST,FLYING,...
14,CROBAT,POISON,FLYING,85,110,80,55,80,130,540,...,1650,90,204,NO_ITEM,...,F50,15,MEDIUM_FAST,FLYING,...
15,BELLSPROUT,GRASS,POISON,50,75,35,70,30,40,300,...,90,255,84,NO_ITEM,...,F50,20,MEDIUM_SLOW,PLANT,...
16,WEEPINBELL,GRASS,POISON,65,95,50,90,45,55,400,...,140,120,151,NO_ITEM,...,F50,20,MEDIUM_SLOW,PLANT,...
17,VICTREEBEL,GRASS,POISON,80,115,65,110,60,70,500,...,340,45,191,NO_ITEM,...,F50,20,MEDIUM_SLOW,PLANT,...
18,ARBOK,POISON,DRAGON,60,90,75,65,70,90,450,...,1430,90,147,NO_ITEM,...,F50,20,MEDIUM_FAST,GROUND,DRAGON
19,MAREEP,ELECTRIC,...,45,35,35,55,40,30,240,...,170,235,59,NO_ITEM,...,F50,20,MEDIUM_SLOW,MONSTER,GROUND
20,FLAAFFY,ELECTRIC,...,65,50,55,70,60,40,340,...,290,120,117,NO_ITEM,...,F50,20,MEDIUM_SLOW,MONSTER,GROUND
21,AMPHAROS,ELECTRIC,DRAGON,95,80,80,125,100,60,540,...,1360,45,194,NO_ITEM,...,F50,20,MEDIUM_SLOW,MONSTER,GROUND
22,SUNFLORA,GRASS,...,70,70,55,100,70,55,420,...,190,120,146,NO_ITEM,...,F50,20,MEDIUM_SLOW,PLANT,...
23,ODDISH,GRASS,POISON,45,50,55,70,60,20,300,...,120,255,78,NO_ITEM,...,F50,20,MEDIUM_SLOW,PLANT,...
24,GLOOM,GRASS,POISON,60,65,70,90,75,40,400,...,190,120,132,NO_ITEM,...,F50,20,MEDIUM_SLOW,PLANT,...
25,POLIWAG,WATER,...,40,50,40,40,40,90,300,...,270,255,77,NO_ITEM,...,F50,20,MEDIUM_SLOW,WATER_1,...
26,DOOMSPARCE,NORMAL,DRAGON,125,95,80,80,75,45,500,...,40,90,175,NO_ITEM,...,F50,20,MEDIUM_FAST,GROUND,...
27,DIGLETT,GROUND,...,10,55,25,30,40,90,250,...,20,255,81,NO_ITEM,...,F50,20,MEDIUM_FAST,GROUND,...
28,DUGTRIO,GROUND,...,35,95,50,50,80,140,450,...,730,50,153,NO_ITEM,...,F50,20,MEDIUM_FAST,GROUND,...
29,FARFETCH_D,FLYING,NORMAL,50,65,50,60,60,65,350,...,330,45,94,NO_ITEM,STICK,F50,20,MEDIUM_FAST,FLYING,GROUND
30,NIDORAN_M,POISON,...,40,60,50,45,35,55,285,...,200,235,60,NO_ITEM,...,F0,20,MEDIUM_SLOW,MONSTER,GROUND
31,NIDORINO,POISON,...,60,80,60,60,60,70,390,...,430,120,118,NO_ITEM,...,F0,20,MEDIUM_SLOW,MONSTER,GROUND
32,NIDOKING,POISON,GROUND,80,100,80,80,60,100,500,...,1370,45,195,NO_ITEM,...,F0,20,MEDIUM_SLOW,MONSTER,GROUND
33,IGGLYBUFF,NORMAL,FAIRY,80,30,15,40,20,15,200,...,20,170,39,NO_ITEM,...,F75,10,FAST,NONE,...
34,JIGGLYPUFF,NORMAL,FAIRY,115,55,30,55,35,30,320,...,120,170,76,NO_ITEM,...,F75,10,FAST,FAIRY,...
35,WIGGLYTUFF,NORMAL,FAIRY,140,85,50,70,50,45,440,...,260,50,109,NO_ITEM,...,F75,10,FAST,FAIRY,...
36,ABRA,PSYCHIC,...,30,25,20,95,50,80,300,...,430,200,73,NO_ITEM,...,F25,20,MEDIUM_SLOW,HUMANSHAPE,...
37,KADABRA,PSYCHIC,...,40,35,30,120,70,105,400,...,1250,100,145,NO_ITEM,...,F25,20,MEDIUM_SLOW,HUMANSHAPE,...
38,ALAKAZAM,PSYCHIC,...,55,50,45,140,85,125,500,...,1060,50,186,NO_ITEM,...,F25,20,MEDIUM_SLOW,HUMANSHAPE,...
39,MACHOP,FIGHTING,...,65,80,50,35,35,35,300,...,430,180,88,NO_ITEM,...,F25,20,MEDIUM_SLOW,HUMANSHAPE,...
40,MACHOKE,FIGHTING,...,80,100,70,50,50,50,400,...,1550,90,146,NO_ITEM,...,F25,20,MEDIUM_SLOW,HUMANSHAPE,...
41,MACHAMP,FIGHTING,...,90,130,80,65,80,55,500,...,2870,45,193,NO_ITEM,...,F25,20,MEDIUM_SLOW,HUMANSHAPE,...
42,GASTLY,GHOST,...,30,35,30,95,35,75,300,...,2,190,95,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...
43,HAUNTER,GHOST,...,45,60,45,100,55,95,400,...,2,90,126,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...
44,GENGAR,GHOST,...,60,85,60,110,75,110,500,...,890,45,190,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,.

In [41]:
flying_mons = df.loc[ (df['HP']>80) | (df['speed']>80) ].reset_index(drop=True)
flying_mons

,species_ID,type_1,type_2,HP,phAtk,phDef,spAtk,spDef,speed,BST,...,weight,catch_rate,base_exp,item_1,item_2,gender_ratio,egg_cycles,growth_rate,egg_group_1,egg_group_2
0,QUILAVA,FIRE,...,60,65,60,85,65,85,420,...,420,45,142,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
1,TYPHLOSION,FIRE,...,80,85,80,105,85,95,530,...,1750,45,209,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
2,FERALIGATR,WATER,...,85,105,90,90,80,80,530,...,1960,45,210,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,WATER_1
3,FURRET,NORMAL,...,85,75,65,45,65,90,425,...,720,90,116,BERRY,GOLD_BERRY,F50,15,MEDIUM_FAST,GROUND,...
4,NOCTOWL,FLYING,GHOST,110,50,50,80,110,70,470,...,900,90,162,NO_ITEM,...,F50,15,MEDIUM_FAST,FLYING,...
5,XATU,FLYING,PSYCHIC,65,60,55,115,70,105,470,...,330,75,171,NO_ITEM,...,F50,20,MEDIUM_FAST,FLYING,...
6,PIKACHU,ELECTRIC,...,35,60,40,75,50,90,350,...,130,190,82,NO_ITEM,BERRY,F50,10,MEDIUM_FAST,GROUND,FAIRY
7,RAICHU,ELECTRIC,...,60,90,55,100,85,110,500,...,660,75,122,NO_ITEM,BERRY,F50,10,MEDIUM_FAST,GROUND,FAIRY
8,TOGEKISS,FAIRY,FLYING,85,50,95,105,100,65,500,...,650,45,214,NO_ITEM,...,F12_5,10,FAST,FLYING,FAIRY
9,LEDIAN,BUG,FLYING,65,85,50,55,110,85,450,...,780,90,134,NO_ITEM,...,F50,15,FAST,BUG,...
10,ARIADOS,BUG,POISON,90,100,80,60,80,40,450,...,740,90,134,NO_ITEM,...,F50,15,FAST,BUG,...
11,GOLBAT,POISON,FLYING,70,80,65,65,75,85,440,...,1210,90,171,NO_ITEM,...,F50,15,MEDIUM_FAST,FLYING,...
12,CROBAT,POISON,FLYING,85,110,80,55,80,130,540,...,1650,90,204,NO_ITEM,...,F50,15,MEDIUM_FAST,FLYING,...
13,ARBOK,POISON,DRAGON,60,90,75,65,70,90,450,...,1430,90,147,NO_ITEM,...,F50,20,MEDIUM_FAST,GROUND,DRAGON
14,LANTURN,WATER,ELECTRIC,115,58,58,76,76,67,450,...,500,75,156,NO_ITEM,...,F50,20,SLOW,WATER_2,...
15,QUAGSIRE,WATER,GROUND,95,85,95,65,75,35,450,...,1650,90,137,NO_ITEM,...,F50,20,MEDIUM_FAST,WATER_1,GROUND
16,AMPHAROS,ELECTRIC,DRAGON,95,80,80,125,100,60,540,...,1360,45,194,NO_ITEM,...,F50,20,MEDIUM_SLOW,MONSTER,GROUND
17,POLIWAG,WATER,...,40,50,40,40,40,90,300,...,270,255,77,NO_ITEM,...,F50,20,MEDIUM_SLOW,WATER_1,...
18,POLIWHIRL,WATER,...,65,70,70,50,50,95,400,...,440,120,131,NO_ITEM,KINGS_ROCK,F50,20,MEDIUM_SLOW,WATER_1,...
19,POLIWRATH,WATER,FIGHTING,90,85,95,70,90,70,500,...,1190,45,185,NO_ITEM,KINGS_ROCK,F50,20,MEDIUM_SLOW,WATER_1,...
20,POLITOED,WATER,FIRE,90,75,75,90,100,70,500,...,750,45,185,NO_ITEM,KINGS_ROCK,F50,20,MEDIUM_SLOW,WATER_1,...
21,DUNSPARCE,NORMAL,...,100,70,70,65,65,30,400,...,310,190,75,NO_ITEM,...,F50,20,MEDIUM_FAST,GROUND,...
22,DOOMSPARCE,NORMAL,DRAGON,125,95,80,80,75,45,500,...,40,90,175,NO_ITEM,...,F50,20,MEDIUM_FAST,GROUND,...
23,DIGLETT,GROUND,...,10,55,25,30,40,90,250,...,20,255,81,NO_ITEM,...,F50,20,MEDIUM_FAST,GROUND,...
24,DUGTRIO,GROUND,...,35,95,50,50,80,140,450,...,730,50,153,NO_ITEM,...,F50,20,MEDIUM_FAST,GROUND,...
25,KANGASKHAN,NORMAL,...,105,105,80,40,80,90,500,...,1760,45,175,NO_ITEM,...,F100,20,MEDIUM_FAST,MONSTER,...
26,SLOWPOKE,WATER,...,95,70,75,45,50,15,350,...,790,190,99,NO_ITEM,KINGS_ROCK,F50,20,MEDIUM_FAST,MONSTER,WATER_1
27,SLOWBRO,WATER,PSYCHIC,95,75,120,100,80,30,500,...,1730,75,164,NO_ITEM,KINGS_ROCK,F50,20,MEDIUM_FAST,MONSTER,WATER_1
28,SLOWKING,WATER,PSYCHIC,95,75,80,100,120,30,500,...,1750,70,164,NO_ITEM,KINGS_ROCK,F50,20,MEDIUM_FAST,MONSTER,WATER_1
29,FORRETRESS,BUG,STEEL,70,80,140,40,60,110,500,...,2770,75,118,NO_ITEM,...,F50,20,MEDIUM_FAST,BUG,...
30,JUMPLUFF,GRASS,FLYING,75,55,70,55,85,110,450,...,70,45,176,NO_ITEM,...,F50,20,MEDIUM_SLOW,FAIRY,PLANT
31,HYPNO,PSYCHIC,...,85,70,70,70,115,65,475,...,1670,75,165,NO_ITEM,...,F50,20,MEDIUM_FAST,HUMANSHAPE,...
32,NIDOQUEEN,POISON,GROUND,100,80,100,60,80,80,500,...,1320,45,194,NO_ITEM,...,F100,20,MEDIUM_SLOW,NONE,...
33,NIDOKING,POISON,GROUND,80,100,80,80,60,100,500,...,1370,45,195,NO_ITEM,...,F0,20,MEDIUM_SLOW,MONSTER,GROUND
34,CLEFABLE,FAIRY,...,90,65,65,80,85,55,440,...,880,25,129,MYSTERYBERRY,MOON_STONE,F75,10,FAST,FAIRY,...
35,JIGGLYPUFF,NORMAL,FAIRY,115,55,30,55,35,30,320,...,120,170,76,NO_ITEM,...,F75,10,FAST,FAIRY,...
36,WIGGLYTUFF,NORMAL,FAIRY,140,85,50,70,50,45,440,...,260,50,109,NO_ITEM,...,F75,10,FAST,FAIRY,...
37,KADABRA,PSYCHIC,...,40,35,30,120,70,105,400,...,1250,100,145,NO_ITEM,...,F25,20,MEDIUM_SLOW,HUMANSHAPE,...
38,ALAKAZAM,PSYCHIC,...,55,50,45,140,85,125,500,...,1060,50,186,NO_ITEM,...,F25,20,MEDIUM_SLOW,HUMANSHAPE,...
39,MACHAMP,FIGHTING,...,90,130,80,65,80,55,500,...,2870,45,193,NO_ITEM,...,F25,20,MEDIUM_SLOW,HUMANSHAPE,...
40,HAUNTER,GHOST,...,45,60,45,100,55,95,400,...,2,90,126,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...
41,GENGAR,GHOST,...,60,85,60,110,75,110,500,...,890,45,190,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,.

In [ ]:
# name of the fastest pokemon
fast = df.sort_values(by=['speed'], ascending=[False]).reset_index(drop=True)
fastest = fast.loc[0, 'species_ID']
fastest

'DUGTRIO'

In [ ]:
# count of normal type pokemons
normies = df.loc[ (df['type_1'] == "NORMAL") | (df['type_2'] == "NORMAL") ].reset_index(drop=True)
len(normies)

12

In [77]:
# name of the fastest fire type pokemon
fire_mons = df.loc[ (df['type_1'] == "FIRE") | (df['type_2'] == "FIRE") ].reset_index(drop=True)
fast_firemon = fire_mons.sort_values(by=['speed'], ascending=[False]).reset_index(drop=True)
fastest = fast_firemon.loc[0, 'species_ID']
fastest

'TYPHLOSION'

In [80]:
ground_type = df.loc[(df['type_1'] == "GROUND") | (df['type_2'] == "GROUND")].reset_index(drop=True)

hp_ground_type = ground_type.loc[(df['HP']>50)].reset_index(drop=True)

len(hp_ground_type)

5